-- Перестань ебаться в глаза и хукать сборку, сделай сам или купи у ｓｕｇｒａａｌ. ｌｕｖ ｓｕｐ#8475
/*------------------------------------------------
					Привилегии
--------------------------------------------------*/
IGS("VIP 30-D", "vip30d"):SetBAdminGroup("VIP", 1)
 	:SetPrice(50)
 	:SetTerm(30)
	:SetDescription("- VIP профессии\n- Отключено ограничение по времени для профессий\n- А так же все остальное, что будет добавляться для VIP в будущем")
 	:SetCategory("Привилегии")
//	:SetIcon("https://i.imgur.com/qYjnfAV.png")

IGS("VIP", "vip"):SetBAdminGroup("VIP", 2)
 	:SetPrice(89)
 	:SetPerma()
	:SetDescription("- VIP профессии\n- Отключено ограничение по времени для профессий\n- А так же все остальное, что будет добавляться для VIP в будущем")
 	:SetCategory("Привилегии")
//	:SetIcon("https://i.imgur.com/mLoHaCE.jpg")

IGS("Moderator 30-D", "dmod30d"):SetBAdminGroup("DModerator", 3)
 	:SetPrice(200)
 	:SetTerm(30)
	:SetDescription("- Всё что дает привилегия ниже (VIP)\n- Команды:\n• /sit - Переместится на админ базу\n• /freeze - Заморозить игрока\n• /mute | /mutevoice | /mutechat - Отключить способ общения игроку\n• /goto | /tp | /return - Перемещение\n• /logs | /pe - Логи игрока(-ов)\n• /menu - Список всех доступных команд, меню\n- Доступ к профессии Модератор\n- Возможность отвечать на жалобы")
 	:SetCategory("Привилегии")
//	:SetIcon("https://i.imgur.com/mLoHaCE.jpg")

IGS("Moderator", "dmod"):SetBAdminGroup("DModerator", 4)
 	:SetPrice(350)
 	:SetPerma()
	:SetDescription("- Всё что дает привилегия ниже (VIP)\n- Команды:\n• /sit - Переместится на админ базу\n• /freeze - Заморозить игрока\n• /mute | /mutevoice | /mutechat - Отключить способ общения игроку\n• /goto | /tp | /return - Перемещение\n• /logs | /pe - Логи игрока(-ов)\n• /menu - Список всех доступных команд, меню\n- Доступ к профессии Модератор\n- Возможность отвечать на жалобы")
 	:SetCategory("Привилегии")
//	:SetIcon("https://i.imgur.com/mLoHaCE.jpg")

IGS("Admin 30-D", "adm30d"):SetBAdminGroup("dadmin", 5)
 	:SetPrice(350)
 	:SetTerm(30)
	:SetDescription("- Всё что дает привилегия ниже (Moderator)\n- Команды:\n• /ban - Выдать бан\n• /setjob - Установить профессию\n• /forceunwant - Снять розыск\n• /forceunarrest - Снять арест\n• /forceunwarrant - Отменить ордер\n• /sethp - Выдать ХП\n• /setarmor - Выдать броню\n• /spectate - Наблюдение за игроком\n- Доступ к профессии Администратор\n- Возможность трогать чужие пропы за профессию Администратора, использовать Noclip")
 	:SetCategory("Привилегии")
//	:SetIcon("https://cdn.discordapp.com/attachments/955817756178133035/1011991349169508372/admin.png")

IGS("Admin", "adm"):SetBAdminGroup("dadmin", 6)
 	:SetPrice(500)
 	:SetPerma()
	:SetDescription("- Всё что дает привилегия ниже (Moderator)\n- Команды:\n• /ban - Выдать бан\n• /setjob - Установить профессию\n• /forceunwant - Снять розыск\n• /forceunarrest - Снять арест\n• /forceunwarrant - Отменить ордер\n• /sethp - Выдать ХП\n• /setarmor - Выдать броню\n• /spectate - Наблюдение за игроком\n- Доступ к профессии Администратор\n- Возможность трогать чужие пропы за профессию Администратора, использовать Noclip")
 	:SetCategory("Привилегии")
//	:SetIcon("https://cdn.discordapp.com/attachments/955817756178133035/1011991349169508372/admin.png")

-- тут надо сделать unlimitedadmin

IGS("SuperAdmin 30-D", "sadm30d"):SetBAdminGroup("DSuperAdmin", 7)
 	:SetPrice(500)
 	:SetTerm(30)
	:SetDescription("- Всё что дает привилегия ниже (Admin)")
 	:SetCategory("Привилегии")
//	:SetIcon("https://cdn.discordapp.com/attachments/955817756178133035/1011991350574579773/superadmin.png")

IGS("SuperAdmin", "sadm"):SetBAdminGroup("DSuperAdmin", 8)
 	:SetPrice(700)
 	:SetPerma()
	:SetDescription("- Всё что дает привилегия ниже (Admin)")
 	:SetCategory("Привилегии")
//	:SetIcon("https://cdn.discordapp.com/attachments/955817756178133035/1011991350574579773/superadmin.png")

-- тут надо сделать unlimitedsuperadmin

IGS("Owner 30-D", "owner30d"):SetBAdminGroup("Owner", 9)
 	:SetPrice(700)
 	:SetTerm(30)
	:SetDescription("- Всё что дает привилегия ниже (Admin)")
 	:SetCategory("Привилегии")
//	:SetIcon("https://cdn.discordapp.com/attachments/955817756178133035/1011991350130004018/owner.png")

IGS("Owner", "owner"):SetBAdminGroup("Owner", 10)
 	:SetPrice(1000)
 	:SetPerma()
	:SetDescription("- Всё что дает привилегия ниже (Admin)")
 	:SetCategory("Привилегии")
//	:SetIcon("https://cdn.discordapp.com/attachments/955817756178133035/1011991350130004018/owner.png")

/*--------------------------------------------------
						Weapons
----------------------------------------------------*/
/*

IGS("Glock 18", "perma_glock")
	:SetCategory("Оружие навсегда")
	:SetPrice(50)
	:SetWeapon("m9k_glock")
	:SetTerm()
	:SetIcon("models/weapons/w_dmg_glock.mdl", true)

IGS("Камера", "perma_camera")
	:SetCategory("Оружие навсегда")
	:SetPrice(20)
	:SetTerm()
	:SetWeapon("gmod_camera")
	:SetIcon("models/MaxOfS2D/camera.mdl", true)

IGS("Монтировка", "perma_crowbar")
	:SetCategory("Оружие навсегда")
	:SetPrice(50)
	:SetTerm()
	:SetWeapon("weapon_crowbar")
	:SetIcon("models/weapons/w_crowbar.mdl", true)

IGS("SIG Sauer P229R", "perma_sig")
	:SetCategory("Оружие навсегда")
	:SetPrice(50)
	:SetTerm()
	:SetWeapon("m9k_sig_p229r")
	:SetIcon("models/weapons/w_sig_229r.mdl", true)

IGS("P08 Luger", "perma_luger")
	:SetCategory("Оружие навсегда")
	:SetPrice(50)
	:SetTerm()
	:SetWeapon("m9k_luger")
	:SetIcon("models/weapons/w_luger_p08.mdl", true)

IGS("S&W Model 500", "perma_sdw500")
	:SetCategory("Оружие навсегда")
	:SetPrice(50)
	:SetTerm()
	:SetWeapon("m9k_model500")
	:SetIcon("models/weapons/w_sw_model_500.mdl", true)

IGS("Desert Eagle", "perma_deagle")
	:SetCategory("Оружие навсегда")
	:SetPrice(50)
	:SetWeapon("m9k_deagle")
	:SetTerm()
	:SetIcon("models/weapons/w_tcom_deagle.mdl", true)

IGS("Raging Bull - Scoped", "perma_ragbull")
	:SetCategory("Оружие навсегда")
	:SetPrice(50)
	:SetTerm()
	:SetWeapon("m9k_scoped_taurus")
	:SetIcon("models/weapons/w_raging_bull_scoped.mdl", true)

IGS("МП-40", "perma_mp40")
	:SetCategory("Оружие навсегда")
	:SetPrice(120)
	:SetTerm()
	:SetWeapon("m9k_mp40")
	:SetIcon("models/weapons/w_mp40smg.mdl", true)

IGS("Kriss Vector", "perma_vector")
	:SetCategory("Оружие навсегда")
	:SetPrice(150)
	:SetTerm()
	:SetWeapon("m9k_vector")
	:SetIcon("models/weapons/w_kriss_vector.mdl", true)

IGS("AAC Honey Badger", "perma_honey")
	:SetCategory("Оружие навсегда")
	:SetPrice(150)
	:SetTerm()
	:SetWeapon("m9k_honeybadger")
	:SetIcon("models/weapons/w_aac_honeybadger.mdl", true)

IGS("Tommy Gun", "perma_tom")
	:SetCategory("Оружие навсегда")
	:SetPrice(100)
	:SetTerm()
	:SetWeapon("m9k_thompson")
	:SetIcon("models/weapons/w_tommy_gun.mdl", true)

IGS("AWP", "perma_awp")
	:SetCategory("Оружие навсегда")
	:SetPrice(200)
	:SetTerm()
	:SetWeapon("swb_awp")
	:SetIcon("models/weapons/w_snip_awp.mdl", true)

IGS("M249", "perma_m249")
	:SetCategory("Оружие навсегда")
	:SetPrice(300)
	:SetTerm()
	:SetWeapon("swb_m249")
	:SetIcon("models/weapons/w_mach_m249para.mdl", true)

IGS("АК-74", "perma_ak74")
	:SetCategory("Оружие навсегда")
	:SetPrice(200)
	:SetTerm()
	:SetWeapon("m9k_ak74")
	:SetIcon("models/weapons/w_tct_ak47.mdl", true)

IGS("HK 416", "perma_hk416")
	:SetCategory("Оружие навсегда")
	:SetPrice(200)
	:SetTerm()
	:SetWeapon("m9k_m416")
	:SetIcon("models/weapons/w_hk_416.mdl", true)	

IGS("SPAS-12", "perma_spas12")
	:SetCategory("Оружие навсегда")
	:SetPrice(450)
	:SetTerm()
	:SetWeapon("m9k_spas12")
    :SetIcon("models/weapons/w_spas_12.mdl", true)	

IGS("СР-3 «Вихрь»", "perma_vih")
	:SetCategory("Оружие навсегда")
	:SetPrice(150)
	:SetTerm()
	:SetWeapon("m9k_vikhr")
    :SetIcon("models/weapons/w_dmg_vikhr.mdl", true)	

IGS("Steyr AUG A3", "perma_aug")
    :SetCategory("Оружие навсегда")
   	:SetPrice(120)
   	:SetTerm()
	:SetWeapon("m9k_auga3")
	:SetIcon("models/weapons/w_auga3.mdl", true)

IGS("ВС ВАЛ", "perma_val")
	:SetCategory("Оружие навсегда")
	:SetPrice(250)
	:SetTerm()
	:SetWeapon("m9k_val")
	:SetIcon("models/weapons/w_dmg_vally.mdl", true)	

IGS("73 Winchester Carbine", "perma_winche")
	:SetCategory("Оружие навсегда")
	:SetPrice(220)
	:SetTerm()
	:SetWeapon("m9k_winchester73")
	:SetIcon("models/weapons/w_winchester_1873.mdl", true)

IGS("SCAR", "perma_scar")
	:SetCategory("Оружие навсегда")
	:SetPrice(150)
	:SetTerm()
	:SetWeapon("m9k_scar")
	:SetIcon("models/weapons/w_fn_scar_h.mdl", true)

IGS("F2000AR", "perma_f2000")
	:SetCategory("Оружие навсегда")
	:SetPrice(229)
	:SetTerm()
	:SetWeapon("m9k_f2000")
	:SetIcon("models/weapons/w_fn_f2000.mdl", true)

IGS("Double Barrel Shotgun", "perma_dbarrel")
	:SetCategory("Оружие навсегда")
	:SetPrice(230)
	:SetTerm()
	:SetWeapon("m9k_dbarrel")
	:SetIcon("models/weapons/w_double_barrel_shotgun.mdl", true)	

IGS("Mossberg 590", "perma_mossberg590")
	:SetCategory("Оружие навсегда")
	:SetPrice(230)
	:SetTerm()
	:SetWeapon("m9k_mossberg590")
	:SetIcon("models/weapons/w_mossberg_590.mdl", true)

IGS("Remington 870", "perma_remington")
	:SetCategory("Оружие навсегда")
	:SetPrice(150)
	:SetTerm()
	:SetWeapon("m9k_remington870")
	:SetIcon("models/weapons/w_remington_870_tact.mdl", true)	

IGS("Striker 12", "perma_striker")
	:SetCategory("Оружие навсегда")
	:SetPrice(270)
	:SetTerm()
	:SetWeapon("m9k_striker12")
	:SetIcon("models/weapons/w_striker_12g.mdl", true)

IGS("Winchester 1897", "perma_wnchester")
	:SetCategory("Оружие навсегда")
	:SetPrice(300)
	:SetTerm()
	:SetWeapon("m9k_1897winchester")
	:SetIcon("models/weapons/w_winchester_1897_trench.mdl", true)

IGS("USAS", "perma_usas")
	:SetCategory("Оружие навсегда")
	:SetPrice(400)
	:SetTerm()
	:SetWeapon("m9k_usas")
	:SetIcon("models/weapons/w_usas_12.mdl", true)

IGS("Winchester 87", "perma_winchester87")
	:SetCategory("Оружие навсегда")
	:SetPrice(210)
	:SetTerm()
	:SetWeapon("m9k_1887winchester")
	:SetIcon("models/weapons/w_winchester_1887.mdl", true)

IGS("SVT 40", "perma_svt40")
	:SetCategory("Оружие навсегда")
	:SetPrice(320)
	:SetTerm()
	:SetWeapon("m9k_svt40")
	:SetIcon("models/weapons/w_svt_40.mdl", true)

IGS("SVD Dragunov", "perma_svd")
	:SetCategory("Оружие навсегда")
	:SetPrice(300)
	:SetTerm()
	:SetWeapon("m9k_dragunov")
	:SetIcon("models/weapons/w_svd_dragunov.mdl", true)	

IGS("Barret M82", "perma_barret")
	:SetCategory("Оружие навсегда")
	:SetPrice(450)
	:SetTerm()
	:SetWeapon("m9k_barret_m82")
	:SetIcon("models/weapons/w_barret_m82.mdl", true)

IGS("Barret M82B", "p_barret82")
	:SetCategory("Оружие навсегда")
	:SetPrice(200)
	:SetTerm()
	:SetWeapon("m9k_m98b")
	:SetIcon("models/weapons/w_barrett_m98b.mdl", true)

IGS("Intervention", "perma_int")
	:SetCategory("Оружие навсегда")
	:SetPrice(200)
	:SetTerm()
	:SetWeapon("m9k_intervention")
	:SetIcon("models/weapons/w_snip_int.mdl", true)

IGS("Dragunov SVU", "perma_svu")
	:SetCategory("Оружие навсегда")
	:SetPrice(450)
	:SetTerm()
	:SetWeapon("m9k_svu")
	:SetIcon("models/weapons/w_dragunov_svu.mdl", true)

IGS("Minigun", "perma_m9k_minigun")
	:SetCategory("Оружие навсегда")
	:SetPrice(999)
	:SetTerm()
	:SetWeapon("m9k_minigun")
	:SetIcon("models/weapons/w_m60_machine_gun.mdl", true)

IGS("Отмычка", "lockpick")
	:SetCategory("Оружие навсегда")
	:SetPrice(50)
	:SetTerm()
	:SetWeapon("lockpick")
	:SetIcon("models/weapons/w_crowbar.mdl", true)
	
IGS("Взломщик", "keypad_cracker")
	:SetCategory("Оружие навсегда")
	:SetPrice(50)
	:SetTerm()
	:SetWeapon("keypad_cracker")
	:SetIcon("models/weapons/w_c4.mdl", true)

/*---------------------------------------------------
						Плюшки
-----------------------------------------------------

IGS("Спиннер", "spinner")
	:SetCategory("Плюшки")
	:SetPrice(20)
	:SetTerm()
	:SetWeapon("weapon_fidget")
	:SetIcon("models/props_workshop/fidget_spinner.mdl", true)

IGS("Говорилка", "ttsdonate")
    :SetCategory("Плюшки")
	:SetPrice(90)
	:SetDiscountedFrom(1000)
    :SetPerma()
    :SetStackable(false)
    :SetDescription("Озвучивает все написанные тобой в чат фразы.")
    :SetOnActivate(function(pl)
        pl:SetNWBool("GovorilkaHave", true)
    end)
    :SetValidator(function(pl)
        pl:SetNWBool("GovorilkaHave", true)
    end)
	
*/